#!/usr/bin/env bash

# Example command: arcmd <path to driver_ranking.py> bnet_dict.out factorGraph.fg base_queries.txt 500 &

driverPath=$1
bnetDictFN=$2
factorGraphFN=$3
baseQueriesFN=$4
MIN=$5

MAX=$((MIN + 500))

nohup $driverPath/driver_ranking.py $bnetDictFN $factorGraphFN $baseQueriesFN > arcmd.out 2> arcmd.log << EOF 
AR 1e-6 $MIN $MAX 100 alarm_ranking.txt 
AQ all_probabilities.txt
EOF
